scorecard:
  output: json
  plugins:
    - basic:
        cr-manifest:
          - "deploy/crds/natives.easyteam.fr_v1alpha1_bot_cr.yaml"
    - olm:
        cr-manifest:
          - "deploy/crds/natives.easyteam.fr_v1alpha1_bot_cr.yaml"
        csv-path: "deploy/olm-catalog/bot-operator/0.0.1/bot-operator.v0.0.1.clusterserviceversion.yaml"

