apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bot-operator
  template:
    metadata:
      labels:
        name: bot-operator
    spec:
      serviceAccountName: bot-operator
      containers:
        - name: bot-operator
          # Replace this with the built image name
          image: quay.io/easyteam/bot-controller:v0.0.1
          command:
          - bot-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "bot-operator"
