apiVersion: v1
kind: Service
metadata:
  name: prometheus-app
  labels:
    app: prometheus-app
spec:
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 8080
  selector:
    app: prometheus-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-app
spec:
  selector:
    matchLabels:
      app: prometheus-app
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus-app
        monitoring: prometheus
    spec:
      containers:
        - name: prometheus-app
          image: easyteam/prometheus-app:1.0.0
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8081
              name: prometheus
---

