kind: Service
apiVersion: v1
metadata:
  name: elasticsearch-logging
  namespace: kube-system
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 9200
      targetPort: 9200
---
kind: Endpoints
apiVersion: v1
metadata:
  name: elasticsearch-logging
  namespace: kube-system
subsets:
- addresses:
  - ip: ${IP_ADDRESS}
  ports:
  - port: 9200
---
apiVersion: v1
kind: Pod
metadata:
  name: debian
  namespace: kube-system
spec:
  containers:
  - name: debian
    image: debian:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
---
