global:

route:

  group_by: ['instance', 'alertname']
  receiver: "default"
  routes:
    - match: 
       severity: critical
      receiver: slack
    - match:
        severity: critical
        receiver: default
receivers:
- name: default
  email_configs:
  - to: "admin@localhost"
    from: "admin@localhost"
    auth_username: "admin@localhost"
    auth_password: "smtppassword"
    smarthost: smtp.localhost:25

- name: slack
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/foo'
    channel: '#prod_health'
    send_resolved: true 
