global:
route:
  group_by: [alertname]
  receiver: email

receivers:
- name: email
  email_configs:
  - to: "admin@localhost"
    from: "admin@localhost"
    auth_username: "smtpusername"
    auth_password: "smtppassword"
    smarthost: localhost:25 
