global:

route:

  group_by: ['instance', 'alertname']
  receiver: "default"
  routes:
    - match: 
       severity: critical
      receiver: slack
    - match:
        severity: critical
        receiver: default
receivers:
- name: default
  email_configs:
  - to: "alertmemanager@gmail.com"
    from: "alertmemanager@gmail.com"
    auth_username: "alertmemanager@gmail.com"
    auth_password: "Azertyuiop1234"
    smarthost: smtp.gmail.com:587

- name: slack
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/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'
    channel: '#prod_health'
    send_resolved: true 
