apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  ports:
    - port: 80
      name: grafana
      protocol: TCP
      targetPort: 3000
  selector:
    app: grafana
