apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - prometheus-clusterrole.yaml
  - prometheus-serviceaccount.yaml
  - prometheus-clusterrolebinding.yaml
  - prometheus-statefulset.yaml
  - prometheus-service.yaml
configMapGenerator:
- name: prometheus
  files:
    - prometheus.yml

