apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
  namespace: outofband
rules:
- apiGroups: 
    - ""
  resources:
    - configmaps
    - secrets
    - nodes
    - pods
    - services
    - resourcequotas
    - replicationcontrollers
    - limitranges
    - persistentvolumeclaims
    - persistentvolumes
    - namespaces
    - endpoints
  verbs: 
    - get
    - list
    - watch
- apiGroups: 
    - ""
  resources:
    - configmaps
  verbs: 
    - get
- nonResourceURLs: 
  - /metrics
  verbs:
    - get
- apiGroups: 
    - apps
  resources:
    - daemonsets
    - deployments
    - replicasets
    - statefulsets
  verbs: 
    - list
    - watch
- apiGroups: 
    - batch
  resources:
    - cronjobs
    - jobs
  verbs:
    - list
    - watch
- apiGroups:
    - autoscaling
  resources:
    - horizontalpodautoscalers
  verbs:
    - list
    - watch
